language:
    php

php:
  - 5.6
  - 7.0

install:
  - pecl channel-update pecl.php.net
  - if [ $TRAVIS_PHP_VERSION = "5.6" ]; then yes '' | pecl -q install -f mongo-stable && php --ri mongo; fi;
  - yes '' | pecl -q install -f mongodb-stable && php --ri mongodb || exit 0

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist

script:
  - composer tests
